name: opcd
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - pip:
    - gensim==4.1.2
    - nltk
    - scikit-learn
    - scipy==1.7.2
    - lxml==4.6.4
    - sentence_transformers==2.1.0
    - matplotlib==3.5.0
