name: osprey-cuda
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - gensim=3.8.3
  - pytorch::torchaudio
  - pytorch::torchvision
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.7
  - ipykernel
  - pandas
  - nltk
  - lxml
  - sentence-transformers
  - torchmetrics
  - matplotlib
  - scikit-learn
  - datasets
  - transformers
  - tokenizers
  - ca-certificates
  - certifi
  - openssl
  - pillow==8.3.2
  - accelerate
