name: osprey-cuda
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - mkl<=2023.1.0
  - gensim=3.8.3
  - pytorch::torchaudio
  - pytorch::torchvision
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.7
  - ipykernel
  - pandas
  - nltk
  - lxml
  - sentence-transformers=2.3.1
  - torchmetrics
  - matplotlib
  - scikit-learn
  - scipy=1.10.1
  - datasets
  - transformers
  - tokenizers
  - ca-certificates
  - certifi
  - openssl
  - pillow=8.3.2
  - accelerate
  - pip
  - pip:
    - sentencepiece
    - ctranslate2==3.24.0
    - evaluate
    - rouge_score
